-- POSTGRES

CREATE SCHEMA SQL_AL;

CREATE TABLE SQL_AL.CAR_MAKE (
  CAR_MAKE_ID BIGSERIAL PRIMARY KEY,
  CAR_MAKE_NAME VARCHAR(60)
);

CREATE TABLE SQL_AL.CAR_MODEL (
  CAR_MODEL_ID BIGSERIAL PRIMARY KEY,
  CAR_MAKE_ID BIGINT,
  CAR_MODEL_NAME VARCHAR(60)
);

ALTER TABLE SQL_AL.CAR_MODEL ADD CONSTRAINT CAR_MODEL_CAR_MAKE_ID_FKEY FOREIGN KEY (CAR_MAKE_ID) REFERENCES SQL_AL.CAR_MAKE (CAR_MAKE_ID);

INSERT INTO SQL_AL.CAR_MAKE (CAR_MAKE_NAME) VALUES
  ('CHEVROLET'),
  ('FORD'),
  ('TOYOTA'),
  ('HYUNDAI');

INSERT INTO SQL_AL.CAR_MODEL (CAR_MAKE_ID, CAR_MODEL_NAME) VALUES
  (1, 'AVEO'),
  (1, 'CHEVROLET'),
  (3, 'PRIUS');
